### ISSUE TITLE
Claims in thread principal can be out of date 

### ISSUE THREAD

**Issue by kgreen24** [stormpath/stormpath-dotnet-owin-middleware#63]
When using the SDK to perform a password grant, using the access token in subsequent calls can provide out of date principal information. This may or may not be an issue using the provided /token route, but our organization does not use it, we do everything through the C# SDK.

To reproduce:

1. Acquire an access token from Stormpath using the SDK.
2. Pass the token to a route with the [Authorize] attribute.
3. Note that the claims on the thread principal are correct, such as the name and email address.
4. Change the username, email address, or both on the user in Stormpath either through the SDK or right through the administrator UI.
5. Repeat steps 1 and 2 above.
6. Note that the claims on the principal are now out of date, the username and email address do not accurately reflect the change made. Even making a call to get the details using the user's HREF are not accurate.

The expectation being that if a new token is acquired, that token should contain completely up to date information.

**Comment by nbarbettini** [comment]
This sounds like a caching issue. The claims in the ClaimsPrincipal should always be up to date, **provided that**

1. The SDK is used as a singleton (only 1 shared instance in your code)
2. If you have multiple web servers, a distributed cache is used for the SDK
3. Changes are made through the SDK and not through the Stormpath Admin UI

You can always try [disabling caching](https://docs.stormpath.com/csharp/product-guide/latest/configuration.html#caching-config) in a test environment to rule out caching as the issue here.

Let me know if you need assistance testing this. 👍

**Comment by kgreen24** [comment]
Thanks @nbarbettini. I turned off caching in code by doing: 
`Client = new ClientConfiguration()
                {
                    BaseUrl = "[the url]",
                    CacheManager = new ClientCacheManagerConfiguration()
                    {
                        Enabled = false
                    }
},`

And then everything worked as I expected.

I'd like to talk to you offline about the impact of turning the caching off, since our application is a WebAPI 2.0 microservice architecture that has a single service for interacting with stormpath, and every other service still references the stormpath middleware but only for token validation on protected routes via the [Authorize] attribute.

**Comment by nbarbettini** [comment]
Okay, that makes sense. The downside (as you might have guessed) is higher API call volume and slightly lower performance because it'll be making more calls to Stormpath.

I'll follow up via email. Thanks @kgreen24!

**Comment by kgreen24** [comment]
Much appreciated.
